export const LoginPageStyle: any = (theme: any) => ({
  mainWrapper: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    textAlign: 'center',
    background: '#000000 !important',
    position: 'relative',
    // top: '40%',
  },
  loginTitle: {
    color: '#ffffff !important',
    fontSize: '32px !important',
    fontWeight: '600 !important',
    marginBottom: '20px !important',
    fontFamily: '"Inter",sans-serif !important',
    overflow: 'initial !important',
    [theme.breakpoints.down('sm')]: {
      fontSize: '25px !important',
    },
  },
  loggedTitle: {
    color: '#ffffff !important',
    fontSize: '20px !important',
    fontWeight: '600 !important',
    fontFamily: '"Inter",sans-serif !important',
    overflow: 'initial !important',
    marginBottom: '10px !important',
    [theme.breakpoints.down('md')]: {
      fontSize: '18px !important',
    },
    [theme.breakpoints.down('md')]: {
      fontSize: '14px !important',
    },
  },
  startWatching: {
    color: '#8f98b2 !important',
    fontFamily: '"Inter",sans-serif !important',
    fontWeight: '550 !important',
    fontSize: '16px !important',
    paddingBottom: '20px !important',
    [theme.breakpoints.down('sm')]: {
      fontSize: '12px !important',
    },
  },
  loginNowTitle: {
    backgroundImage: 'linear-gradient(120deg,#0858E3,  50%,#062997)',
    margin: '0 auto !important',
    border: '0 !important',
    borderRadius: '8px !important',
    boxShadow: 'rgba(151, 65, 252, 0.2) 0 15px 30px -5px',
    boxSizing: 'borderBox !important',
    color: ' #FFFFFF !important',
    display: 'flex !important',
    alignItems: 'center !important',
    fontFamily: 'Phantomsans, sans-serif !important',
    fontSize: '20px !important',
    fontWeight: '600 !important',
    justifyContent: 'center',
    lineHeight: '1em !important',
    padding: '19px 24px !important',
    textDecoration: 'none',
    userSelect: 'none !important',
    touchAction: 'manipulation',
    whiteSpace: 'nowrap',
    cursor: 'pointer !important',
    width: '250px !important',
    transition: 'all 0.2s ease-in-out !important',
    textTransform: 'capitalize !important',
    '&:hover': {
      scale: '1.02',
      transform: 'all 0.2s ease-in-out !important',
    },
    [theme.breakpoints.down('md')]: {
      fontSize: '14px !important',
      height: '10px',
      width: '40% !important',
    },
    [theme.breakpoints.down(420)]: {
      fontSize: '11px  !important',
    },
  },

  helpBtn: {
    backgroundImage: 'transparent',
    margin: '0 auto !important',
    border: '0 !important',
    borderRadius: '8px !important',
    boxShadow: 'rgba(151, 65, 252, 0.2) 0 15px 30px -5px',
    boxSizing: 'borderBox !important',
    color: ' #FFFFFF !important',
    display: 'flex !important',
    alignItems: 'center !important',
    fontFamily: 'Phantomsans, sans-serif !important',
    fontSize: '20px !important',
    fontWeight: '600 !important',
    justifyContent: 'center',
    lineHeight: '1em !important',
    padding: '19px 24px !important',
    textDecoration: 'none',
    userSelect: 'none !important',
    touchAction: 'manipulation',
    whiteSpace: 'nowrap',
    cursor: 'pointer !important',
    width: '250px !important',
    transition: 'all 0.2s ease-in-out !important',
    textTransform: 'capitalize !important',
    '&:hover': {
      scale: '1.02',
      transform: 'all 0.2s ease-in-out !important',
    },
    [theme.breakpoints.down('md')]: {
      fontSize: '14px !important',
      height: '10px',
      width: '30% !important',
    },
    [theme.breakpoints.down(420)]: {
      fontSize: '11px  !important',
    },
  },

  modalWrapper: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    background: '#16181f !important',
    // background: '#ffffff !important',
    transform: 'translate(-50%, -50%)',
    padding: '20px',
  },
  modalTopBody: {
    marginBottom: '200px',
  },
  closeIconBox: {
    display: 'flex',
    justifyContent: 'end',
  },
  closeIcon: {
    color: '#ffffff !important',
  },
  modalLoginTitle: {
    fontSize: '24px !important',
    fontFamily: '"Inter",sans-serif !important',
    fontWeight: '600 !important',
    color: '#ffffff !important',
  },
  modalInputBox: {
    margin: '10px 0px',
    display: 'flex',
  },
  modalCountryCode: {
    textAlign: 'center',
    width: '60px',
    fontWeight: '600 !important',
    fontFamily: '"Inter",sans-serif !important',
    marginRight: '10px !important',
    border: '1px solid #8f98b2 !important',
    borderRadius: '4px',
    '.css-14s5rfu-MuiFormLabel-root-MuiInputLabel-root': {
      color: '#8f98b2 !important',
      fontWeight: '600 !important',
    },
  },
  modalPhonenumber: {
    border: '1px solid #8f98b2 !important',
    borderRadius: '4px',
    '.css-9ddj71-MuiInputBase-root-MuiOutlinedInput-root ': {
      color: '#8f98b2 !important',
      '& input[type=number]': {
        '-moz-appearance': 'textfield !important',
      },
      '& input[type=number]::-webkit-outer-spin-button': {
        '-webkit-appearance': 'none',
        margin: '0 !important',
      },
      '& input[type=number]::-webkit-inner-spin-button': {
        '-webkit-appearance': 'none',
        margin: '0 !important',
      },
    },
    '.css-14s5rfu-MuiFormLabel-root-MuiInputLabel-root': {
      color: '#8f98b2 !important',
    },
    '.css-1d3z3hw-MuiOutlinedInput-notchedOutline': {
      borderColor: '#8f98b2 !important',
    },
    '.css-14lo706': {
      color: '#8f98b2 !important',
    },
  },
  modalByProceeding: {
    fontFamily: '"Inter",sans-serif !important',
    fontSize: '12px !important',
    color: '#8f98b2 !important',
  },
  modalHavingtroubleBox: {
    display: 'flex',
    justifyContent: 'center',
  },
  modalHavingtrouble: {
    marginRight: '10px',
    color: '#8f98b2 !important',
    paddingBottom: '20px',
  },
  modalGetHelp: {
    color: '#3586f0 !important',
    fontFamily: '"Inter",sans-serif',
    fontWeight: '600',
  },
  loggedTitleBox: {
    display: 'flex',
    flexDirection: 'column',
    textAlign: 'start',
  },

  loggedTitleBox2: {
    display: 'flex',
    height: '60px',
    marginRight: '10px',
    [theme.breakpoints.down(420)]: {
      flexWrap: 'wrap !important',
    },
  },
  loggedBoxWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'relative',
    width: '95%',
    marginTop: '1rem',
    [theme.breakpoints.down('sm')]: {
      width: '90%',
    },
  },
  recaptchaStyle: {
    position: 'absolute',
    zIndex: '1',
    left: '60px',
  },
  watchLaterListBox: {
    display: 'flex',
    flexDirection: 'column !important',
    justifyContent: 'space-between',
    marginTop: '20%',
  },
  GenreBtn: {
    marginLeft: '25px',
    fontFamily: '"Inter",sans-serif !important',
    fontWeight: '600',
    fontSize: '20px !important',
    textTransform: 'capitalize !important',
    color: '#ffffff !important',
  },
  viewAllBtn: {
    marginRight: '25px',
    fontFamily: '"Inter",sans-serif !important',
    fontWeight: '600',
    fontSize: '20px !important',
    textTransform: 'capitalize !important',
    color: '#8f98b2 !important',
    '&:hover': {
      color: '#ffffff !important',
    },
  },
  wrapperBtn: {
    display: 'flex',
    justifyContent: 'space-between',
  },
});
